# -*- coding: utf-8 -*-
"""split

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/156JSeqzld29AprFvKmFYfOU_6e_ShRAT
"""

import xml.etree.ElementTree as ET

mytree = ET.parse('ABSA16_Restaurants_Train_SB1_v2.xml')
myroot = mytree.getroot()

reviews = myroot.findall("Review")

count = 1
iter = 0
"""Ρουτίνα χωρισμού του xml σε 10 τμήματα. Το xml περιέχει περίπου 350 προτάσεις, όπότε με αυτή τη λογική προκύπτει το 35 ως ο αναμενόμενος αριθμός προτάσεων
 που θα περιέχει το καθένα από τα 10 τμήματα."""
while (count <= 10):
    tree = ET.Element("Root")
    for i in range(iter, iter + 35):
        tree.append(reviews[i])
    
    """μετατροπή σε string"""
    b_xml = ET.tostring(tree)
    """Για κάθε τμήμα, φτιάχνουμε το αντίστοιχο xml αρχείο."""
    with open("part" + str(count) + ".xml", "wb") as f:
        f.write(b_xml)
    iter += 35
    count += 1

mytree2 = ET.parse('part1.xml')
myroot2 = mytree2.getroot()

reviews2 = myroot2.findall("Review")

#print(len(reviews2))

mytree2 = ET.parse('part2.xml')
myroot2 = mytree2.getroot()

reviews2 = myroot2.findall("Review")

#print(len(reviews2))

mytree2 = ET.parse('part3.xml')
myroot2 = mytree2.getroot()

reviews2 = myroot2.findall("Review")

#print(len(reviews2))

mytree2 = ET.parse('part4.xml')
myroot2 = mytree2.getroot()

reviews2 = myroot2.findall("Review")

#print(len(reviews2))

mytree2 = ET.parse('part5.xml')
myroot2 = mytree2.getroot()

reviews2 = myroot2.findall("Review")

#print(len(reviews2))

mytree2 = ET.parse('part6.xml')
myroot2 = mytree2.getroot()

reviews2 = myroot2.findall("Review")

#print(len(reviews2))

mytree2 = ET.parse('part7.xml')
myroot2 = mytree2.getroot()

reviews2 = myroot2.findall("Review")

#print(len(reviews2))

mytree2 = ET.parse('part8.xml')
myroot2 = mytree2.getroot()

reviews2 = myroot2.findall("Review")

#print(len(reviews2))

mytree2 = ET.parse('part9.xml')
myroot2 = mytree2.getroot()

reviews2 = myroot2.findall("Review")

#print(len(reviews2))

mytree2 = ET.parse('part10.xml')
myroot2 = mytree2.getroot()

reviews2 = myroot2.findall("Review")

#print(len(reviews2))